routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'COhome@index');
//Route::get('/about', 'COgame@about');
//Route::get('/gamelist','COgame@gamelist');
Route::get('/contact','COgame@contact');
Route::get('/game/{id}','COgame@show');

Route::resource('managegame','COmanagegame');
Route::resource('admingamelist','COadmingame');

//hudya
Route::resource('admindeveloper','COadmindeveloper');
Route::resource('admingenre','COadmingenre');
Route::resource('adminplatform','COadminplatform');
Route::resource('adminage','COadminage');

//baru
Route::resource('searchgame','COgamesearch');
//

//end hudya

Route::resource('game','COgame');
Route::resource('home','COhome');
Route::resource('signin','COsignin');
Route::resource('signup','COsignup'); //bikin controller dengan --resource
Route::resource('adminsignup','COadminsignup'); //view, controller
Route::resource('adminsignin','COadminsignin');
Route::resource('signout','COsignout');
Route::resource('adminsignout','COadminsignout');
Route::resource('adminlist','COadminlist');

resources/views/frontend/about.blade.php
@extends('frontend.base') <!--memanggil dari base -->
@section('content')

        <!-- about-->
<div class="about-agileinfo" id="about">
    <div class="container">
        <h2>About Us</h2>
        <div class="about-grids-w3-agileits">
            <div class="col-md-6 about-grid-left-agileits-w3layouts">
                <ul>
                    <li><i>1.</i><a class="link link--kumya" href="single.html"><span data-letters="Qui ratione voluptatem dolores eos qui">Qui ratione voluptatem dolores</span></a></li>
                    <li><i>2.</i><a class="link link--kumya" href="single.html"><span data-letters="Dolores eos qui ratione voluptatem sequi">Dolores eos qui ratione volu</span></a></li>
                    <li><i>3.</i><a class="link link--kumya" href="single.html"><span data-letters="Voluptatem quia voluptas sit asper">Voluptatem quia voluptas sit asper</span></a></li>
                    <li><i>4.</i><a class="link link--kumya" href="single.html"><span data-letters="Consectetur adipiscing elit, incid">Consectetur adipiscing elit, incid</span></a></li>
                    <li><i>5.</i><a class="link link--kumya" href="single.html"><span data-letters="Quia voluptas sit aspernatur aut odit">Quia voluptas sit aspernatur aut</span></a></li>
                    <li><i>6.</i><a class="link link--kumya" href="single.html"><span data-letters="Eos qui ratione voluptatem sequi">Eos qui ratione voluptatem sequi</span></a></li>
                </ul>
            </div>
            <div class="col-md-6 about-grid-right-w3-agile">
                <div class="grid-w3ls">
                    <figure class="effect-zoe">
                        <img src="/assets/frontend/images/about.jpg" alt=" " class="img-responsive" />
                        <figcaption>
                            <h3>Games<span>Zone</span></h3>
                            <p class="icon-links">
                                <a href="#"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></a>
                                <a href="#"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
                                <a href="#"><span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span></a>
                            </p>
                            <p class="description">Suspendisse convallis malesuada libero, non rutrum arcu pellentesque lacinia.</p>
                        </figcaption>
                    </figure>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //about -->



<!-- team -->
<div class="team-w3layouts">
    <div class="container">
        <h3>Our Team</h3>
        <div class="w3l_team_grids-agile">
            <div class="col-md-3 w3l_team_grid">
                <div class="view view-second">
                    <img src="/assets/frontend/images/t1.jpg" alt=" " class="img-responsive" />
                    <div class="mask"></div>
                    <div class="content">
                        <div class="w3l_social_icons w3l_social_icons1">
                            <ul>
                                <li><a href="#" class="linkedin"></a></li>
                                <li><a href="#" class="google"></a></li>
                                <li><a href="#" class="twitter"></a></li>
                                <li><a href="#" class="facebook"></a></li>
                            </ul>
                        </div>
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
                    </div>
                </div>
                <h4>Mariya Thomas</h4>
                <p>Games Designer</p>
            </div>
            <div class="col-md-3 w3l_team_grid">
                <div class="view view-second">
                    <img src="/assets/frontend/images/t2.jpg" alt=" " class="img-responsive" />
                    <div class="mask"></div>
                    <div class="content">
                        <div class="w3l_social_icons w3l_social_icons1">
                            <ul>
                                <li><a href="#" class="linkedin"></a></li>
                                <li><a href="#" class="google"></a></li>
                                <li><a href="#" class="twitter"></a></li>
                                <li><a href="#" class="facebook"></a></li>
                            </ul>
                        </div>
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
                    </div>
                </div>
                <h4>Dino Jass</h4>
                <p>Games Designer</p>
            </div>
            <div class="col-md-3 w3l_team_grid">
                <div class="view view-second">
                    <img src="/assets/frontend/images/t3.jpg" alt=" " class="img-responsive" />
                    <div class="mask"></div>
                    <div class="content">
                        <div class="w3l_social_icons w3l_social_icons1">
                            <ul>
                                <li><a href="#" class="linkedin"></a></li>
                                <li><a href="#" class="google"></a></li>
                                <li><a href="#" class="twitter"></a></li>
                                <li><a href="#" class="facebook"></a></li>
                            </ul>
                        </div>
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
                    </div>
                </div>
                <h4>Michael Doe</h4>
                <p>Games Designer</p>
            </div>
            <div class="col-md-3 w3l_team_grid">
                <div class="view view-second">
                    <img src="/assets/frontend/images/t4.jpg" alt=" " class="img-responsive" />
                    <div class="mask"></div>
                    <div class="content">
                        <div class="w3l_social_icons w3l_social_icons1">
                            <ul>
                                <li><a href="#" class="linkedin"></a></li>
                                <li><a href="#" class="google"></a></li>
                                <li><a href="#" class="twitter"></a></li>
                                <li><a href="#" class="facebook"></a></li>
                            </ul>
                        </div>
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
                    </div>
                </div>
                <h4>Rita James</h4>
                <p>Games Designer</p>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //team -->


@endsection

resources/views/frontend/contact.blade.php
@extends('frontend.base')
@section('content')

<!-- banner -->
<div class="contact-agileinfo">
    <div class="container">
        <h2>Reach Us</h2>
        <div class="col-md-4 contact-left-agile">
            <div class="address-w3-agileits" id="address">
                <h4>Address</h4>
                <address>
                    <ul>
                        <li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> Parma Via Modena</li>
                    </ul>
                </address>
            </div>
            <div class="phone-agileits-w3layouts" id="phone">
                <h4>Phone</h4>
                <p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> +1 (734) 123-4567</p>
            </div>
            <div class="email">
                <h4>Email</h4>
                <p><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <a href="mailto:mail@example.com"> info@example.com</a></p>
            </div>
        </div>
        <div class="col-md-8 contact-right-w3">
            <form action="#" method="post">
                <input type="text" class="text" name="Name" placeholder="Name" required="">
                <input type="text" class="text" name="Email" placeholder="Email" required="">
                <input type="text" class="text" name="Phone" placeholder="Phone" required="">
                <input type="text" class="text" name="City" placeholder="City" required="">
                <textarea name="Message" placeholder="Message" required=""></textarea>
                <input type="submit" class="more_btn" value="Send Message">
            </form>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

<!-- Map-iFrame -->
<div class="map" id="map">
    <div class="map-hover">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d22702.22744502486!2d11.113366067229226!3d44.662878362361056!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x477fc3eca9065c15%3A0x12ec8a03aadae866!2s40019+Sant&#39;Agata+Bolognese+BO%2C+Italy!5e0!3m2!1sen!2sin!4v1451281303075" allowfullscreen></iframe>
        <div class="map-hover-1"></div>
    </div>
</div>
<!-- //Map-iFrame -->

@endsection

resources/views/frontend/gamelist.blade.php
@extends('frontend.base')
@section('content')


    <div class ="events-w3layouts">
        <h2>Game List</h2>
        <div class="clearfix">

        </div>

    </div>
    <div class="events-section2-agileinfo">

        <div class="container">
            @foreach($game as $value) <!-- Looping variable game di namakan sebagai value -->
            <div class="blog1-w3ls">
                <div class="col-md-4 blog-image-w3l">
                    <a href="single.html"><img src="{{ asset('upload/game/'.$value->game_picture) }}" alt=" " /></a>
                </div>
    <div class="col-md-8">
        <a href="single.html"><h2>{{ $value->game_title }}</h2></a>
        <div class="item_info">
            <ul>
                <li><a href="#"><i class="glyphicon glyphicon-user"></i>{{ $value->name_admin }}</a></li>
                <li><i class="glyphicon glyphicon-calendar"></i>{{ $value->created_at }}</li>
                <li><a href="#"><i class="glyphicon glyphicon-comment"></i>{{ $value->genre }}</a></li>
            </ul>
        </div>
        <p> <b> Game Platform : </b>{{ $value->platform }}</p>
        <p> <b> Game Developer : </b>{{ $value->developer }}</p>
        <p> <b> Game Rating : </b> <br>
            <?php
            $rating3 = DB::table('tb_user_rating')
                        ->join('tb_game', 'tb_user_rating.id_game', '=','tb_game.id')
                        ->select(DB::raw('COUNT( tb_user_rating.average ) as jumlah')
                            , DB::raw('AVG( tb_user_rating.average ) as avgg'))
                        ->where('tb_user_rating.id_game', '=' , $value->id)
                        ->get();
                        ?>
            @foreach($rating3 as $a)
                @if(($a->jumlah) == 0)
                    Not Yet Rating
                @endif
                @if(($a->jumlah) >= 1)
                    @if(($a->avgg) == 0)
                        @foreach($agelow as $x)
                            <img style="height: 100px; width: 100px;" src="{{ asset('upload/rating/'.$x->picture) }}" alt=" " />
                        @endforeach
                    @endif
                    @if((($a->avgg) <= 1.3333) && ($a->avgg) > 0)
                        @foreach($agemed as $x)
                            <img style="height: 100px; width: 100px;" src="{{ asset('upload/rating/'.$x->picture) }}" alt=" " />
                        @endforeach
                    @endif
                    @if((($a->avgg) < 3) && ($a->avgg) > 1.3333)
                        @foreach($agemed as $x)
                            <img style="height: 100px; width: 100px;" src="{{ asset('upload/rating/'.$x->picture) }}" alt=" " />
                        @endforeach
                    @endif
                @endif
                @endforeach
            <br>



        <a href="{{route('game.show',$value->id)}}" class="blog-read" >Read More</a>
    </div>
    <div class="clearfix"></div>
                <hr style="border-style: solid none; border-width: 1px 0; margin: 18px 0;">
    </div>

            @endforeach
            {{ $game->links() }}

   <!-- <div class="blog2-w3ls">
        <div class="col-md-4 blog-image-w3l">
            <a href="single.html"><img src="/assets/frontend/images/ng2.jpg" alt=" " /></a>
        </div>
        <div class="col-md-8 blog-text-w3ls">
            <a href="single.html"><h4>In finibus vel metus</h4></a>
            <div class="item_info">
                <ul>
                    <li><a href="#"><i class="glyphicon glyphicon-user"></i>Admin</a></li>
                    <li><i class="glyphicon glyphicon-calendar"></i>17.Aug.2017</li>
                    <li><a href="#"><i class="glyphicon glyphicon-comment"></i>20 Comments</a></li>
                    <li><a href="#"><i class="glyphicon glyphicon-heart"></i>300 Likes</a></li>
                </ul>
            </div>
            <p>Aliquam suscipit neque massa, eu maximus felis gravida vel. Vestibulum lacinia risus risus, ut iaculis felis fermentum id. Cras at vulputate velit, vitae vestibulum augue. Etiam lorem nunc, mattis ac dignissim sit amet, varius et ex. Phasellus eleifend nibh justo, pulvinar cursus sapien commodo non.</p>
            <a href="single.html" class="blog-read" >Read More</a>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="blog3-w3ls">
        <div class="col-md-4 blog-image-w3l">
            <a href="single.html"><img src="/assets/frontend/images/ng3.jpg" alt=" " /></a>
        </div>
        <div class="col-md-8 blog-text-w3ls">
            <a href="single.html"><h4>Nam eget ligula eu</h4></a>
            <div class="item_info">
                <ul>
                    <li><a href="#"><i class="glyphicon glyphicon-user"></i>Admin</a></li>
                    <li><i class="glyphicon glyphicon-calendar"></i>24.Aug.2015</li>
                    <li><a href="#"><i class="glyphicon glyphicon-comment"></i>20 Comments</a></li>
                    <li><a href="#"><i class="glyphicon glyphicon-heart"></i>300 Likes</a></li>
                </ul>
            </div>
            <p>Aliquam suscipit neque massa, eu maximus felis gravida vel. Vestibulum lacinia risus risus, ut iaculis felis fermentum id. Cras at vulputate velit, vitae vestibulum augue. Etiam lorem nunc, mattis ac dignissim sit amet, varius et ex. Phasellus eleifend nibh justo, pulvinar cursus sapien commodo non.</p>
            <a href="single.html" class="blog-read" >Read More</a>
        </div>
        <div class="clearfix"></div>
    </div> -->

    </div>
    </div>


@endsection

resources/views/frontend/searchgame.blade.php
@extends('frontend.base')
@section('content')


    <div class ="events-w3layouts">
        <h2>Game List</h2>
        <div class="clearfix">

        </div>

    </div>
    <div class="events-section2-agileinfo">
        @if(Session::has('alert-success'))
            <div class="alert alert-success">
                <center>{{ Session::get('alert-success') }}</center>
            </div>
        @endif
        <div class="container">
            @foreach($games as $value) <!-- Looping variable game di namakan sebagai value -->
            <div class="blog1-w3ls">
                <div class="col-md-4 blog-image-w3l">
                    <a href="single.html"><img src="{{ asset('upload/game/'.$value->game_picture) }}" alt=" " /></a>
                </div>
                <div class="col-md-8">
                    <a href="single.html"><h2>{{ $value->game_title }}</h2></a>
                    <div class="item_info">
                        <ul>
                            <li><a href="#"><i class="glyphicon glyphicon-user"></i>{{ $value->name_admin }}</a></li>
                            <li><i class="glyphicon glyphicon-calendar"></i>{{ $value->created_at }}</li>
                            <li><a href="#"><i class="glyphicon glyphicon-comment"></i>{{ $value->genre }}</a></li>
                        </ul>
                    </div>
                    <p> <b> Game Description : </b>{{ $value->game_description }}</p>
                    <p> <b> Game Platform : </b>{{ $value->platform }}</p>
                    <br>
                    <p> <b> Game Rating : </b> <br><img style="height: 100px; width: 100px;" src="{{ asset('upload/rating/'.$value->rating) }}" alt=" " /></p> <!-- memakai src karena gambar nya dynamis (memakai banyak gambar)-->

                    <a href="{{route('game.show',$value->id)}}" class="blog-read" >Read More</a>
                </div>
                <div class="clearfix"></div>
            </div>

            @endforeach

                    <!-- <div class="blog2-w3ls">
        <div class="col-md-4 blog-image-w3l">
            <a href="single.html"><img src="/assets/frontend/images/ng2.jpg" alt=" " /></a>
        </div>
        <div class="col-md-8 blog-text-w3ls">
            <a href="single.html"><h4>In finibus vel metus</h4></a>
            <div class="item_info">
                <ul>
                    <li><a href="#"><i class="glyphicon glyphicon-user"></i>Admin</a></li>
                    <li><i class="glyphicon glyphicon-calendar"></i>17.Aug.2017</li>
                    <li><a href="#"><i class="glyphicon glyphicon-comment"></i>20 Comments</a></li>
                    <li><a href="#"><i class="glyphicon glyphicon-heart"></i>300 Likes</a></li>
                </ul>
            </div>
            <p>Aliquam suscipit neque massa, eu maximus felis gravida vel. Vestibulum lacinia risus risus, ut iaculis felis fermentum id. Cras at vulputate velit, vitae vestibulum augue. Etiam lorem nunc, mattis ac dignissim sit amet, varius et ex. Phasellus eleifend nibh justo, pulvinar cursus sapien commodo non.</p>
            <a href="single.html" class="blog-read" >Read More</a>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="blog3-w3ls">
        <div class="col-md-4 blog-image-w3l">
            <a href="single.html"><img src="/assets/frontend/images/ng3.jpg" alt=" " /></a>
        </div>
        <div class="col-md-8 blog-text-w3ls">
            <a href="single.html"><h4>Nam eget ligula eu</h4></a>
            <div class="item_info">
                <ul>
                    <li><a href="#"><i class="glyphicon glyphicon-user"></i>Admin</a></li>
                    <li><i class="glyphicon glyphicon-calendar"></i>24.Aug.2015</li>
                    <li><a href="#"><i class="glyphicon glyphicon-comment"></i>20 Comments</a></li>
                    <li><a href="#"><i class="glyphicon glyphicon-heart"></i>300 Likes</a></li>
                </ul>
            </div>
            <p>Aliquam suscipit neque massa, eu maximus felis gravida vel. Vestibulum lacinia risus risus, ut iaculis felis fermentum id. Cras at vulputate velit, vitae vestibulum augue. Etiam lorem nunc, mattis ac dignissim sit amet, varius et ex. Phasellus eleifend nibh justo, pulvinar cursus sapien commodo non.</p>
            <a href="single.html" class="blog-read" >Read More</a>
        </div>
        <div class="clearfix"></div>
    </div> -->

        </div>
    </div>


@endsection

resources/views/frontend/signin.blade.php
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>Sign In - KIDS.GO</title>
    <!-- custom-theme -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Esteem Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
        function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //custom-theme -->
    <link href="/assets/frontenduser/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/assets/frontenduser/css/snow.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/assets/frontenduser/css/component.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/assets/frontenduser/css/style_grid.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/assets/frontenduser/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- font-awesome-icons -->
    <link href="/assets/frontenduser/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
</head>
<body>
<!-- /pages_agile_info_w3l -->

<div class="pages_agile_info_w3l">
    <!-- /login -->
    <div class="over_lay_agile_pages_w3ls">
        <div class="registration">

            <div class="signin-form profile">
                @if(Session::has('alert-success'))
                    <div class="alert alert-danger">
                        <center>{{ Session::get('alert-success') }}</center>
                    </div>
                @endif
                <h2>Sign in Form</h2>
                <div class="login-form">
                    <form action="{{route('signin.store')}}" method="post">

                        {{csrf_field()}}

                        <input type="email" name="email" placeholder="E-mail" required="">
                        <input type="password" name="password" placeholder="Password" required="">
                        <div class="tp">
                            <input type="submit" value="SIGN IN">
                        </div>
                    </form>
                </div>

                <p><a href="/signup"> Don't have an account?</a></p>

                <h6><a href="/">Back To Home</a><h6>
            </div>
        </div>
        <!--copy rights start here-->
        <div class="copyrights_agile">
            <p>© 2017 KIDS.GO </p>
        </div>
        <!--copy rights end here-->
    </div>
</div>
<!-- /login -->
<!-- //pages_agile_info_w3l -->


<!-- js -->

<script type="/assets/frontenduser/text/javascript" src="js/jquery-2.1.4.min.js"></script>
<script src="/assets/frontenduser/js/modernizr.custom.js"></script>

<script src="/assets/frontenduser/js/classie.js"></script>
<script src="/assets/frontenduser/js/gnmenu.js"></script>
<script>
    new gnMenu( document.getElementById( 'gn-menu' ) );
</script>

<!-- //js -->

<script src="/assets/frontenduser/js/screenfull.js"></script>
<script>
    $(function () {
        $('#supported').text('Supported/allowed: ' + !!screenfull.enabled);

        if (!screenfull.enabled) {
            return false;
        }



        $('#toggle').click(function () {
            screenfull.toggle($('#container')[0]);
        });
    });
</script>
<script src="/assets/frontenduser/js/jquery.nicescroll.js"></script>
<script src="/assets/frontenduser/js/scripts.js"></script>
<script src="/assets/frontenduser/js/snow.js"></script>
<script type="/assets/frontenduser/text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-36251023-1']);
    _gaq.push(['_setDomainName', 'jqueryscript.net']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>
<script type="/assets/frontenduser/text/javascript" src="js/bootstrap-3.1.1.min.js"></script>


</body>
</html>

resources/views/frontend/signup.blade.php
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>User Signup</title>
    <!-- custom-theme -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Esteem Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
        function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //custom-theme -->
    <link href="/assets/frontenduser/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/assets/frontenduser/css/snow.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/assets/frontenduser/css/component.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/assets/frontenduser/css/style_grid.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/assets/frontenduser/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- font-awesome-icons -->
    <link href="/assets/frontenduser/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
</head>
<body>
<!-- /pages_agile_info_w3l -->

<div class="pages_agile_info_w3l">
    <!-- /login -->
    <div class="over_lay_agile_pages_w3ls two">
        <div class="registration">

            <div class="signin-form profile">
                <h2>Sign up Form</h2>

                @if(Session::has('alert-success'))
                    <div class="alert alert-sucess">
                        {{Session::get('alert-success')}}

                     </div>
                @endif

                <div class="login-form">
                    <form action="{{route('signup.store')}}" method="post">
                        {{csrf_field()}} <!-- input data harus memasuki csrf -->

                        <input type="text" name="fName" placeholder="First Name" required="">
                        <input type="text" name="lName" placeholder="Last Name" required="">
                        <input type="email" name="email" placeholder="E-mail" required="">
                        <input type="password" name="password" placeholder="Password" required="">
                        <select name="gender" id="selector1" class="form-control1">
                            <option>-- Gender --</option>
                            <option value="Male">Pria</option>
                            <option value="Female">Wanita</option>
                        </select>
                        <div class="tp">
                            <input type="submit" value="SIGN Up">
                        </div>
                    </form>
                </div>

                <p> By clicking Sign Up, I agree to your terms</p>

                <h6><a href="/">Back To Home</a><h6>
            </div>
        </div>
        <!--copy rights start here-->
        <div class="copyrights_agile two">
            <p>© 2017 KIDS.GO </p>
        </div>
        <!--copy rights end here-->
    </div>
</div>
<!-- /login -->
<!-- //pages_agile_info_w3l -->


<!-- js -->

<script type="text/javascript" src="/assets/frontenduser/js/jquery-2.1.4.min.js"></script>
<script src="/assets/frontenduser/js/modernizr.custom.js"></script>

<script src="/assets/frontenduser/js/classie.js"></script>
<script src="/assets/frontenduser/js/gnmenu.js"></script>
<script>
    new gnMenu( document.getElementById( 'gn-menu' ) );
</script>

<!-- //js -->

<script src="js/screenfull.js"></script>
<script>
    $(function () {
        $('#supported').text('Supported/allowed: ' + !!screenfull.enabled);

        if (!screenfull.enabled) {
            return false;
        }



        $('#toggle').click(function () {
            screenfull.toggle($('#container')[0]);
        });
    });
</script>
<script src="/assets/frontenduser/js/jquery.nicescroll.js"></script>
<script src="/assets/frontenduser/js/scripts.js"></script>
<script src="/assets/frontenduser/js/snow.js"></script>
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-36251023-1']);
    _gaq.push(['_setDomainName', 'jqueryscript.net']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>
<script type="text/javascript" src="/assets/frontenduser/js/bootstrap-3.1.1.min.js"></script>


</body>
</html>