routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'COhome@index');
//Route::get('/about', 'COgame@about');
//Route::get('/gamelist','COgame@gamelist');
Route::get('/contact','COgame@contact');
Route::get('/game/{id}','COgame@show');

Route::resource('managegame','COmanagegame');
Route::resource('admingamelist','COadmingame');

//hudya
Route::resource('admindeveloper','COadmindeveloper');
Route::resource('admingenre','COadmingenre');
Route::resource('adminplatform','COadminplatform');
Route::resource('adminage','COadminage');

//baru
Route::resource('searchgame','COgamesearch');
//

//end hudya

Route::resource('game','COgame');
Route::resource('home','COhome');
Route::resource('signin','COsignin');
Route::resource('signup','COsignup'); //bikin controller dengan --resource
Route::resource('adminsignup','COadminsignup'); //view, controller
Route::resource('adminsignin','COadminsignin');
Route::resource('signout','COsignout');
Route::resource('adminsignout','COadminsignout');
Route::resource('adminlist','COadminlist');

resources/views/backend/adddeveloper.blade.php
@extends('backend.base')
@section('content')

        <!--banner-->
<div class="banner">

    <h2>
        <a href="index.html">Home</a>
        <i class="fa fa-angle-right"></i>
        <span>Add Game</span>
    </h2>
</div>
<!--//banner-->



<div class="grid-form">
    <div class="grid-form1">
        <h3 id="forms-example" class="">Form Game</h3>
        @if ($errors->any())
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><em>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </em>
            </div>
        @endif
        <form action="{{route('admindeveloper.store')}}" method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Name" name="name">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Description</label>
                <textarea type="text" class="form-control" id="exampleInputPassword1" placeholder="" name="description"></textarea>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/backend/addgame.blade.php
@extends('backend.base')
@section('content')

        <!--banner-->
<div class="banner">

    <h2>
        <a href="index.html">Home</a>
        <i class="fa fa-angle-right"></i>
        <span>Add Game</span>
    </h2>
</div>
<!--//banner-->

    <div class="grid-form">
        <div class="grid-form1">
            <h3 id="forms-example" class="">Form Game</h3>
            <form action="{{route('admingamelist.store')}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="exampleInputEmail1">Game Title</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="game_title" required="">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Game Description</label>
                    <textarea type="text" class="form-control" id="exampleInputPassword1" placeholder="Password" name="description"></textarea>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Rating</label>
                    <select class="form-control" name="rating">
                        @foreach($age as $x2)
                            <option value="{{$x2->id}}">{{$x2->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Genre</label>
                    <select class="form-control" name="genre">
                        @foreach($genre as $x2)
                            <option value="{{$x2->id}}">{{$x2->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Platform</label>
                    <select class="form-control" name="platform">
                        @foreach($platform as $x2)
                            <option value="{{$x2->id}}">{{$x2->name}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">Developer</label>
                    <select class="form-control" name="developer">
                        @foreach($developer as $x2)
                            <option value="{{$x2->id}}">{{$x2->name}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">Price</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Nama" name="price" required="">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Game Release</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Nama" name="release" required="">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Game Access</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Nama" name="access" required="">
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">Game Picture</label>
                    <input type="file" class="form-control" id="exampleInputEmail1" placeholder="Nama" name="gambar" required="">
                </div>

                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/backend/addgenre.blade.php
@extends('backend.base')
@section('content')

        <!--banner-->
<div class="banner">

    <h2>
        <a href="index.html">Home</a>
        <i class="fa fa-angle-right"></i>
        <span>Add Game</span>
    </h2>
</div>
<!--//banner-->

<div class="grid-form">
    <div class="grid-form1">
        <h3 id="forms-example" class="">Form Game</h3>
        <form action="{{route('admingenre.store')}}" method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Name" name="name" required="">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Description</label>
                <textarea type="text" class="form-control" id="exampleInputPassword1" placeholder="" name="description" required=""></textarea>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/backend/admingamelist.blade.php
@extends('backend.base')
@section('content')

        <!--banner-->
<div class="banner">

    <h2>
        <a href="index.html">Home</a>
        <i class="fa fa-angle-right"></i>
        <span>Game List</span>
    </h2>
</div>
<!--//banner-->

    <div class="content-top">
        <div class="col-md-12 ">
            <div class="content-top-1">
                <table class="table table-bordered" id="data">
                    <h3>Daftar Game</h3>
                    @if(Session::has('alert-success'))
                        <div class="alert alert-success">
                            {{ Session::get('alert-success') }}
                        </div>
                    @endif
                    <br>
                    <thead>
                    <tr>
                        <th>No.</th>
                        <th>Game Title</th>
                        <th>Game Description</th>
                        <th>Date</th>
                        <th>Genre</th>
                        <th>Developer</th>
                        <th>Action</th>
                        <!--<th>Admin</th>
                        <th>Developer</th>
                        <th>Price</th>
                        <th>Game Release</th>
                        <th>Game Access</th>
                        <th>Picture</th>-->
                    </tr>
                    </thead>
                    <tbody>
                    <?php $no=1; ?>
                    @foreach($game as $value)
                        <tr>
                            <th scope="row">{{ $no++ }}</th>
                            <td>{{ $value->game_title }}</td>
                            <td>{{ $value->game_description }}</td>
                            <td>{{ $value->created_at }}</td>
                            <td>{{ $value->nama_genre }}</td>
                            <td>{{ $value->nama_developer }}</td>
                            <td>
                                <form method="POST" action="{{ route('admingamelist.destroy', $value->id) }}" accept-charset="UTF-8">
                                    <input name="_method" type="hidden" value="DELETE">
                                    <input name="_token" type="hidden" value="{{ csrf_token() }}">
                                    <a class="btn-sm btn-info"  href="{{route('admingamelist.edit', $value->id)}}">Edit Game</a>
                                    <input type="submit" class="btn btn-warning btn-sm" onclick="return confirm('Anda yakin akan menghapus data ?');" value="Delete">
                                </form></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>

    </div>
@endsection

resources/views/backend/adminhome.blade.php
@extends('backend.base') <!--memanggil dari base -->
@section('content')

        <!--banner-->
<div class="banner">

    <h2>
        <a href="index.html">Home</a>
        <i class="fa fa-angle-right"></i>
        <span>Dashboard</span>
    </h2>
</div>
<!--//banner-->
<!--content-->
<br>
<center><h2>WELCOME TO KIDS.GO ADMIN</h2></center>
<br>


    @endsection

resources/views/backend/adminsignin.blade.php
<!DOCTYPE HTML>
<html>
<head>
    <title>Admin Sign In - KIDS.GO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Minimal Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="/assets/backend/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
    <!-- Custom Theme files -->
    <link href="/assets/backend/css/style.css" rel='stylesheet' type='text/css' />
    <link href="/assets/backend/css/font-awesome.css" rel="stylesheet">
    <script src="/assets/backend/js/jquery.min.js"> </script>
    <script src="/assets/backend/js/bootstrap.min.js"> </script>
</head>
<body>
<div class="login">
    <h1><a href="index.html">KIDS.GO </a></h1>
    <div class="login-bottom">
        <h2>Sign In</h2>

        <form action="{{route('adminsignin.store')}}" method="post"> <!-- isi csrf di bagian form-->

            {{csrf_field()}}

            <div class="col-md-6">
                <div class="login-mail">
                    <input type="text" placeholder="Email" required="" name="email">
                    <i class="fa fa-envelope"></i>
                </div>
                <div class="login-mail">
                    <input type="password" placeholder="Password" required="" name="password">
                    <i class="fa fa-lock"></i>
                </div>

                <!--<a class="news-letter " href="#">
                    <label class="checkbox1"><input type="checkbox" name="checkbox" ><i> </i>Forget Password</label>
                </a> -->


            </div>
            <div class="col-md-6 login-do">
                <label class="hvr-shutter-in-horizontal login-sub">
                    <input type="submit" value="login">
                </label>
                <center><p><b>Do not have an account? Contact your Supervisor</b></p></center>
               <!-- <a href="{{route('adminsignup.index')}}" class="hvr-shutter-in-horizontal">Signup</a> -->
            </div>

            <div class="clearfix"> </div>
        </form>
    </div>
</div>
<!---->
<div class="copy-right">
    <p> &copy; 2017 KIDS.GO </p>
</div>
<!---->
<!--scrolling js-->
<script src="/assets/backend/js/jquery.nicescroll.js"></script>
<script src="/assets/backend/js/scripts.js"></script>
<!--//scrolling js-->
</body>
</html>

resources/views/backend/base.blade.php
<!DOCTYPE HTML>
<html>
<head>
    <title>KIDS.GO Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Minimal Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="/assets/backend/application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="/assets/backend/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
    <!-- Custom Theme files -->
    <link href="/assets/backend/css/style.css" rel='stylesheet' type='text/css' />
    <link href="/assets/backend/css/font-awesome.css" rel="stylesheet">
    <script src="/assets/backend/js/jquery.min.js"> </script>
    <!-- Mainly scripts -->
    <script src="/assets/backend/js/jquery.metisMenu.js"></script>
    <script src="/assets/backend/js/jquery.slimscroll.min.js"></script>

    <!-- Script JQuery Data Table -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.js"></script>

    <!--tiny MCE base -->
    <script src="/assets/backend/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>

    <!-- Custom and plugin javascript -->
    <link href="/assets/backend/css/custom.css" rel="stylesheet">
    <script src="/assets/backend/js/custom.js"></script>
    <script src="/assets/backend/js/screenfull.js"></script>
    <script>
        $(function () {
            $('#supported').text('Supported/allowed: ' + !!screenfull.enabled);

            if (!screenfull.enabled) {
                return false;
            }



            $('#toggle').click(function () {
                screenfull.toggle($('#container')[0]);
            });



        });
    </script>

    <!----->

    <!--pie-chart--->
    <script src="/assets/backend/js/pie-chart.js" type="text/javascript"></script>
    <script type="/assets/backend/text/javascript">

        $(document).ready(function () {
            $('#demo-pie-1').pieChart({
                barColor: '#3bb2d0',
                trackColor: '#eee',
                lineCap: 'round',
                lineWidth: 8,
                onStep: function (from, to, percent) {
                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');
                }
            });

            $('#demo-pie-2').pieChart({
                barColor: '#fbb03b',
                trackColor: '#eee',
                lineCap: 'butt',
                lineWidth: 8,
                onStep: function (from, to, percent) {
                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');
                }
            });

            $('#demo-pie-3').pieChart({
                barColor: '#ed6498',
                trackColor: '#eee',
                lineCap: 'square',
                lineWidth: 8,
                onStep: function (from, to, percent) {
                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');
                }
            });


        });

    </script>
    <!--skycons-icons-->
    <script src="/assets/backend/js/skycons.js"></script>
    <!--//skycons-icons-->
</head>
<body>
<div id="wrapper">

    <!----->
    <nav class="navbar-default navbar-static-top" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <h1> <a class="navbar-brand" href="/admin">KIDS.GO Admin</a></h1>
        </div>
        <div class=" border-bottom">
            <div class="full-left">
                <section class="full-top">
                    <button id="toggle"><i class="fa fa-arrows-alt"></i></button>
                </section>

                <div class="clearfix"> </div>
            </div>


            <!-- Brand and toggle get grouped for better mobile display -->

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="drop-men" >
                <ul class=" nav_1">


                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle dropdown-at" data-toggle="dropdown"><span class=" name-caret">{{session()->get ('nameadmin')}}<i class="caret"></i></span><img src="/assets/backend/images/wo.jpg"></a>
                        <ul class="dropdown-menu " role="menu">
                            <li><a href="profile.html"><i class="fa fa-user"></i>Edit Profile</a></li>
                            <li><a href="{{route('adminsignout.index')}}"><i class="fa fa-user"></i>Sign out</a></li>
                        </ul>
                    </li>

                </ul>
            </div><!-- /.navbar-collapse -->
            <div class="clearfix">

            </div>

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">

                        <li>
                            <a href="/admin" class=" hvr-bounce-to-right"><i class="fa fa-dashboard nav_icon "></i><span class="nav-label">Dashboards</span> </a>
                        </li>

                        <li>
                            <a href="#" class=" hvr-bounce-to-right"><i class="fa fa-indent nav_icon"></i> <span class="nav-label">Manage Game</span><span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="{{route('admingamelist.index')}}" class=" hvr-bounce-to-right"><i class="fa fa-align-left nav_icon"></i>Game List</a></li>
                                <li><a href="{{route('admingamelist.create')}}" class="hvr-bounce-to-right"><i class="fa fa-file-text-o nav_icon"></i>Create Game Review</a></li>

                            </ul>
                        </li>

                        <li>
                            <a href="#" class=" hvr-bounce-to-right"><i class="fa fa-list nav_icon"></i> <span class="nav-label">Manage user</span><span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="maps.html" class=" hvr-bounce-to-right"><i class="fa fa-map-marker nav_icon"></i>User List</a></li>
                                <li><a href="{{route('adminlist.index')}}"class=" hvr-bounce-to-right"> <i class="fa fa-info-circle nav_icon"></i>Admin List</a></li>
                            </ul>
                        </li>

                        <li>
                            <a href="#" class=" hvr-bounce-to-right"><i class="fa fa-cog nav_icon"></i> <span class="nav-label">Settings</span><span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="{{route('adminsignout.index')}}" class=" hvr-bounce-to-right"><i class="fa fa-sign-in nav_icon"></i>Signout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
    </nav>
    <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="content-main">



            @yield('content')
            <!--//content-->



            <!---->
            <div class="copy">
                <p> &copy; 2017 KIDS.GO </p>
            </div>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<!---->

<!--data tables-->
<script type="text/javascript">
    $(document).ready(function(){
        $('#data').DataTable(); <!-- # baca ke id, kalau . ke class-->
    });
</script>

<!--scrolling js-->
<script src="/assets/backend/js/jquery.nicescroll.js"></script>
<script src="/assets/backend/js/scripts.js"></script>
<!--//scrolling js-->
<script src="/assets/backend/js/bootstrap.min.js"> </script>
</body>
</html>

resources/views/backend/developerlist.blade.php
@extends('backend.base')
@section('content')

    <div class="content-top">
        <div class="col-md-12 ">
            <div class="content-top-1">
                <table class="table table-bordered" id="data">
                    <h3>Admin List</h3>
                    @if(Session::has('alert-success'))
                        <div class="alert alert-success">
                            {{ Session::get('alert-success') }}
                        </div>
                    @endif
                    <br>
                    <thead>
                    <tr>
                        <th>No.</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Aksi</th>

                    </tr>
                    </thead>
                    <tbody>
                    <?php $no=1; ?>
                    @foreach($developer as $value)
                        <tr>
                            <th scope="row">{{ $no++ }}</th>
                            <td>{{ $value->name }}</td>
                            <td>{{ $value->description }}</td>
                            <td>
                                <form method="POST" action="{{ route('admindeveloper.destroy', $value->id) }}" accept-charset="UTF-8">
                                    <input name="_method" type="hidden" value="DELETE">
                                    <input name="_token" type="hidden" value="{{ csrf_token() }}">
                                    <a class="btn-sm btn-info"  href="{{route('admindeveloper.edit', $value->id)}}">Edit Developer</a>
                                    <input type="submit" class="btn btn-warning btn-sm" onclick="return confirm('Anda yakin akan menghapus data ?');" value="Delete">
                                </form></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>

    </div>

@endsection

resources/views/backend/editage.blade.php
@extends('backend.base')
@section('content')

        <!--banner-->
<div class="banner">

    <h2>
        <a href="index.html">Home</a>
        <i class="fa fa-angle-right"></i>
        <span>Add Game</span>
    </h2>
</div>
<!--//banner-->

<div class="grid-form">
    <div class="grid-form1">
        <h3 id="forms-example" class="">Form Game</h3>
        <form action="{{route('adminage.update', $age->id)}}" method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Name" name="name" required="" value="{{$age->name}}">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Description</label>
                <textarea type="text" class="form-control" id="exampleInputPassword1" placeholder="" name="description" required="">{{$age->description}}</textarea>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Description</label>
                <input type="file" class="form-control" id="exampleInputEmail1" placeholder="Name" name="file">
                <br>
                <img src="{{asset('upload/rating/'.$age->picture)}}" style="height: 150px; width: 150px;"/>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
            {{ method_field('PUT') }}
        </form>
    </div>
</div>
@endsection

resources/views/backend/editgenre.blade.php
@extends('backend.base')
@section('content')

        <!--banner-->
<div class="banner">

    <h2>
        <a href="index.html">Home</a>
        <i class="fa fa-angle-right"></i>
        <span>Add Game</span>
    </h2>
</div>
<!--//banner-->

<div class="grid-form">
    <div class="grid-form1">
        <h3 id="forms-example" class="">Form Game</h3>
        <form action="{{route('admingenre.update', $genre->id)}}" method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Name" name="name" required="" value="{{$genre->name}}">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Description</label>
                <textarea type="text" class="form-control" id="exampleInputPassword1" placeholder="" name="description" required="">{{$genre->description}}</textarea>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
            {{ method_field('PUT') }}
        </form>
    </div>
</div>
@endsection

resources/views/backend/editplatform.blade.php
@extends('backend.base')
@section('content')

        <!--banner-->
<div class="banner">

    <h2>
        <a href="index.html">Home</a>
        <i class="fa fa-angle-right"></i>
        <span>Add Game</span>
    </h2>
</div>
<!--//banner-->

<div class="grid-form">
    <div class="grid-form1">
        <h3 id="forms-example" class="">Form Game</h3>
        <form action="{{route('adminplatform.update', $platform->id)}}" method="post" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Name" name="name" required="" value="{{$platform->name}}">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Description</label>
                <textarea type="text" class="form-control" id="exampleInputPassword1" placeholder="" name="description" required="">{{$platform->description}}</textarea>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
            {{ method_field('PUT') }}
        </form>
    </div>
</div>
@endsection

resources/views/backend/listage.blade.php
@extends('backend.base')
@section('content')

    <div class="content-top">
        <div class="col-md-12 ">
            <div class="content-top-1">
                <table class="table table-bordered" id="data">
                    <h3>Admin List</h3>
                    @if(Session::has('alert-success'))
                        <div class="alert alert-success">
                            {{ Session::get('alert-success') }}
                        </div>
                    @endif
                    <br>
                    <thead>
                    <tr>
                        <th>No.</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Picture</th>
                        <th>Aksi</th>

                    </tr>
                    </thead>
                    <tbody>
                    {{$no=1 }}
                    @foreach($age as $value)
                        <tr>
                            <th scope="row">{{ $no++ }}</th>
                            <td>{{ $value->name }}</td>
                            <td>{{ $value->description }}</td>
                            <td><img src="{{asset('upload/rating/'.$value->picture)}}" style="width: 105px; height: 105px;"></td>
                            <td>
                                <form method="POST" action="{{ route('adminage.destroy', $value->id) }}" accept-charset="UTF-8">
                                    <input name="_method" type="hidden" value="DELETE">
                                    <input name="_token" type="hidden" value="{{ csrf_token() }}">
                                    <a class="btn-sm btn-info"  href="{{route('adminage.edit', $value->id)}}">Edit Developer</a>
                                    <input type="submit" class="btn btn-warning btn-sm" onclick="return confirm('Anda yakin akan menghapus data ?');" value="Delete">
                                </form></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>

    </div>

@endsection